### ISSUE TITLE
 Pouch throw an error WebSqlPouchCore.call is not a function

### ISSUE THREAD

**Issue by yurimorini** [pouchdb-community/pouchdb-adapter-cordova-sqlite#78]
When I try to instantiate the plugin, Pouch throw an error `WebSqlPouchCore.call is not a function`. Seems that the very first line of the inclusion require a module:

```
var WebSqlPouchCore = require('pouchdb-adapter-websql-core')
```

The above module export an object with its `default` property ad the needed function cause Pouch db uses ES6 modules and this plugin uses `require`.

So the above line needs to be modified as:

```
var WebSqlPouchCore = require('pouchdb-adapter-websql-core').default
```

**Comment by carolgit** [comment]
How to do that in typescript call ex: import cordovaSqlitePlugin from 'pouchdb-adapter-cordova-sqlite'?


WebSqlPouchCore.call is not a function

**Comment by georgeMuraveiAlkh** [comment]
The same problem. Is there way to fix without waiting and changes in source code?

**Comment by brodybits** [comment]
Perhaps try <https://www.npmjs.com/package/patch-package>

**Comment by lincolnthree** [comment]
Newcomer here. Any movement on this issue? I just ran into it.

**Comment by syc-pad** [comment]
Same issue here... it's a bit annoying... :-/

**Comment by paolosanchi** [comment]
this is fixed in master, waiting the release you can try this:

npm install pouchdb-community/pouchdb-adapter-cordova-sqlite#master --save

**Comment by TDola** [comment]
Problem still happens for me.  Do I need websql plugin installed as well as sql-lite plugin to get this to work?

**Comment by TDola** [comment]
I have the same error, tried with master and still have the problem.  I am using sql-lite-storage, no websql plugins.  Do I need to have one installed?
